language: vi

pipeline: #null
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 3

  - name: DIETClassifier #CRFEntityExtractor #DIETClassifier #MitieEntityExtractor
    epochs: 100
    constrain_similarities: true
    model_confidence: linear_norm #softmax
  - name: EntitySynonymMapper

  # - name: ResponseSelector
  #   epochs: 100
  #   constrain_similarities: true
  #   model_confidence: linear_norm #softmax

  # - name: FallbackClassifier
  #   threshold: 0.5
  #   ambiguity_threshold: 0.1


policies:
  - name: RulePolicy

  - name: MemoizationPolicy
    max_history: 3

  - name: TEDPolicy
    max_history: 3
    epochs: 100
  #   constrain_similarities: true
  #   # model_confidence: cosine

  - name: MappingPolicy
  - name: FallbackPolicy
    nlu_threshold: 0.1
    core_threshold: 0.1
    fallback_action_name: 'utter_fallback'

# policies:
#   - name: MemoizationPolicy
#   - name: TEDPolicy
#     max_history: 3
#     epochs: 100
#   - name: MappingPolicy
#   - name: FallbackPolicy
#     nlu_threshold: 0.6
#     core_threshold: 0.3
#     fallback_action_name: 'utter_fallback'
